# Generated by Django 2.0.2 on 2018-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
